"""Ordered Ticket 114 acceptance cases.

The registry is deliberately data-only.  Each entry names one independently
visible unittest method; tests that exercise a matrix must expose every matrix
row as a named ``subTest`` with an independent assertion.
"""

CASE_REGISTRY = (
    # 114-A1 -- independently readable and mutable settings.
    ("114-A1-C01", "test_ticket114_settings_controls.test_114_a1_c01_timezone_field_update", "timezone update returns old and new values, the resulting settings-object version, and effective time"),
    ("114-A1-C02", "test_ticket114_settings_controls.test_114_a1_c02_contact_window_field_update", "contact-window update preserves its range and returns old and new values, object version, and effective time"),
    ("114-A1-C03", "test_ticket114_settings_controls.test_114_a1_c03_expression_style_field_update", "expression-style update returns old and new values without using current-head generation as an object version"),
    ("114-A1-C04", "test_ticket114_settings_controls.test_114_a1_c04_proactive_contact_preference_update", "proactive-contact preference updates independently"),
    ("114-A1-C05", "test_ticket114_settings_controls.test_114_a1_c05_concurrent_field_update", "concurrent field updates do not overwrite an independently committed value"),
    ("114-A1-C06", "test_ticket114_settings_controls.test_114_a1_c06_invalid_iana_timezone", "invalid IANA timezone is rejected without state change"),
    ("114-A1-C07", "test_ticket114_settings_controls.test_114_a1_c07_invalid_contact_window", "invalid contact window is rejected without state change"),
    ("114-A1-C08", "test_ticket114_settings_controls.test_114_a1_c08_notification_new_task_toggle", "new-task notification moves from not-configured to an explicit owner choice independently"),
    ("114-A1-C09", "test_ticket114_settings_controls.test_114_a1_c09_notification_ordinary_stage_change_toggle", "ordinary-stage-change notification moves from not-configured to an explicit owner choice independently"),
    ("114-A1-C10", "test_ticket114_settings_controls.test_114_a1_c10_notification_care_reminder_toggle", "care-reminder notification moves from not-configured to an explicit owner choice independently"),
    ("114-A1-C11", "test_ticket114_settings_controls.test_114_a1_c11_notification_task_terminal_toggle", "task-terminal notification moves from not-configured to an explicit owner choice independently"),
    ("114-A1-C12", "test_ticket114_settings_controls.test_114_a1_c12_notification_review_summary_toggle", "review-summary notification moves from not-configured to an explicit owner choice independently"),
    ("114-A1-C13", "test_ticket114_settings_controls.test_114_a1_c13_exact_replay", "exact settings-command replay returns the same committed result"),
    ("114-A1-C14", "test_ticket114_contract.test_114_a1_c14_single_field_command_rejects_settings_blob_or_multi_field", "settings command names exactly one field and rejects blob or multi-field mutation"),
    ("114-A1-C15", "test_ticket114_contract.test_114_a1_c15_notification_kind_enum_is_exactly_five", "notification kind contract contains exactly the five ordinary categories"),
    ("114-A1-C16", "test_ticket114_settings_controls.test_114_a1_c16_notifications_start_not_configured_without_defaults", "all five notifications start explicitly not-configured when no owner choice exists"),
    ("114-A1-C17", "test_ticket114_authority_integration.test_114_a1_c17_ticket111_preferences_seed_authoritative_settings", "Ticket 111 contact-window and preference facts seed the authoritative settings projection while notifications remain explicitly not-configured"),
    ("114-A1-C18", "test_ticket114_authority_integration.test_114_a1_c18_finalized_status_recovers_exact_settings_result", "finalized owner mutation status retains the exact old value, new value, settings-object version, and effective time without retaining health or correction bodies"),

    # 114-A2 -- independent controls and current-control rejudgment.
    ("114-A2-C01", "test_ticket114_settings_controls.test_114_a2_c01_control_cartesian_product_preserves_independence", "control Cartesian product leaves every unnamed control unchanged"),
    ("114-A2-C02", "test_ticket114_settings_controls.test_114_a2_c02_stale_generation_control_rejected", "old-generation control command is rejected without state change"),
    ("114-A2-C03", "test_ticket114_settings_controls.test_114_a2_c03_concurrent_revoke_linearizes_once", "concurrent approval revocation linearizes to one authoritative result"),
    ("114-A2-C04", "test_ticket114_settings_controls.test_114_a2_c04_unknown_effect_is_not_rewritten_as_unsent", "revocation preserves an external effect whose result is unknown"),
    ("114-A2-C05", "test_ticket114_settings_controls.test_114_a2_c05_recording_resume_does_not_backfill", "recording resume does not backfill content from the stopped interval"),
    ("114-A2-C06", "test_ticket114_settings_controls.test_114_a2_c06_unsent_effect_is_rejudged_against_current_controls", "an unsent effect is rejudged against current controls"),
    ("114-A2-C07", "test_ticket114_contract.test_114_a2_c07_control_command_names_exactly_one_explicit_control", "control command contract names exactly one explicit control"),
    ("114-A2-C08", "test_ticket114_authority_integration.test_114_a2_c08_recording_stop_blocks_real_daily_body_commit", "recording stop blocks a real new health-body daily commit without changing prior DailyHealthState"),
    ("114-A2-C09", "test_ticket114_authority_integration.test_114_a2_c09_recording_stop_allows_temporary_answer_without_body", "recording stop still allows a body-free temporary owner answer without adding evidence or portrait state"),
    ("114-A2-C10", "test_ticket114_authority_integration.test_114_a2_c10_recording_stop_preserves_owner_correction_right", "recording stop preserves the owner's Ticket 112 correction path while the correction source body is released"),
    ("114-A2-C11", "test_ticket114_authority_integration.test_114_a2_c11_recording_stop_never_persists_body_on_planner_failure", "a stopped-recording source is persisted body-free even when planning fails and the store is reopened"),
    ("114-A2-C12", "test_ticket114_authority_integration.test_114_a2_c12_exact_redelivery_rehydrates_only_transient_stopped_body", "after restart exact redelivery can transiently resume a body-free answer while persistent storage remains body-free"),
    ("114-A2-C13", "test_ticket114_authority_integration.test_114_a2_c13_delayed_first_delivery_from_exclusion_is_not_backfilled", "after recording resumes, a first delivery whose protocol timestamp falls inside a committed recording exclusion remains body-free and cannot backfill DailyHealthState"),
    ("114-A2-C14", "test_ticket114_authority_integration.test_114_a2_c14_recording_excluded_native_alias_is_body_free_from_creation", "after recording resumes, a new causal alias of an exact recording-excluded native event is body-free from its first durable receipt"),
    ("114-A2-C15", "test_ticket114_authority_integration.test_114_a2_c15_failed_stopped_planner_releases_transient_body", "a stopped-recording planner failure releases its transient plaintext source before returning"),
    ("114-A2-C16", "test_ticket114_authority_integration.test_114_a2_c16_stopped_prepare_rejection_receipt_is_body_free", "a stopped-recording turn.prepare rejection stores only a command digest and exact response, never the evidence or portrait candidate body"),
    ("114-A2-C17", "test_ticket114_authority_integration.test_114_a2_c17_missing_event_time_after_exclusion_fails_closed", "after a recording exclusion, a source without protocol event time cannot be proven non-backlog and remains body-free without changing DailyHealthState"),
    ("114-A2-C18", "test_ticket114_authority_integration.test_114_a2_c18_missing_runtime_releases_transient_body", "a stopped-recording source releases its transient plaintext when no daily runtime is available and no durable turn owns recovery"),
    ("114-A2-C19", "test_ticket114_authority_integration.test_114_a2_c19_status_failure_releases_transient_body", "a post-admission daily-status failure releases stopped-recording plaintext before the public receive call returns"),
    ("114-A2-C20", "test_ticket114_authority_integration.test_114_a2_c20_admission_commit_rollback_releases_transient_body", "an inbound receipt commit rollback releases stopped-recording plaintext even though its durable source row was rolled back"),
    ("114-A2-C21", "test_ticket114_authority_integration.test_114_a2_c21_temporary_completion_failure_releases_transient_body", "a body-free temporary-answer evidence stage does not retain stopped-recording plaintext after completion fails, and exact redelivery can rehydrate retry"),
    ("114-A2-C22", "test_ticket114_authority_integration.test_114_a2_c22_correction_cas_owns_transient_body_until_finalize", "the unresolved correction CAS chain alone owns transient source plaintext through prepare and commit, persistent receipts remain body-free, and finalize releases it"),
    ("114-A2-C23", "test_ticket114_authority_integration.test_114_a2_c23_recording_stop_rejects_echoing_temporary_draft", "recording stop rejects any non-canonical temporary draft that echoes, fragments, or transforms owner health text before any durable daily row is written"),
    ("114-A2-C24", "test_ticket114_authority_integration.test_114_a2_c24_recording_stop_rejects_echoing_temporary_terminal", "recording stop rejects an echoing temporary path before a successful terminal can retain transformed owner text in body-free Skill-use facts"),
    ("114-A2-C25", "test_ticket114_authority_integration.test_114_a2_c25_recording_stop_rejects_mixed_correction_scope", "an exact correction maintenance request cannot exempt an additional unapproved evidence claim or its derived artifacts from the recording-stop gate"),
    ("114-A2-C26", "test_ticket114_authority_integration.test_114_a2_c26_recording_stop_rejects_echoing_correction_completion", "a stopped-recording correction may persist its exact maintenance stage but owner prepare rejects any completion that echoes source plaintext into portrait reasons or terminal facts"),
    ("114-A2-C27", "test_ticket114_authority_integration.test_114_a2_c27_recording_stop_rejects_unbound_correction_stage", "a stopped source cannot persist a forged correction stage unless its exact maintenance request was first formed through the managed-rights correction seam"),
    ("114-A2-C28", "test_ticket114_authority_integration.test_114_a2_c28_rejected_owner_prepare_releases_correction_plaintext", "an owner prepare rejection with no durable owner transition releases transient stopped-recording correction plaintext while retaining only the body-free evidence stage"),
    ("114-A2-C29", "test_ticket114_authority_integration.test_114_a2_c29_prepared_correction_has_one_durable_body_copy", "an accepted correction prepare keeps the replacement health body only in Ticket 112's daily aggregate while the owner recovery aggregate retains body-free identity, digest, and daily-turn references"),
    ("114-A2-C30", "test_ticket114_authority_integration.test_114_a2_c30_stopped_correction_handoff_recovers_after_restart", "after restart the public owner-correction submission seam consumes an exact managed-draft re-registration plus exact stopped-source redelivery, tolerates a retryable runtime pause, and reaches the normal owner prepare-commit-finalize chain without caller access to internal runtime or draft state"),
    ("114-A2-C31", "test_ticket114_authority_integration.test_114_a2_c31_public_correction_handoff_rejects_wrong_body", "the public owner-correction handoff rejects a causal replay with different source plaintext and never persists the hostile body or an owner mutation"),
    ("114-A2-C32", "test_ticket114_authority_integration.test_114_a2_c32_public_correction_handoff_requires_reregistration", "after restart the public owner-correction handoff rejects an exact stopped-source redelivery until the owner recreates the exact managed correction draft"),
    ("114-A2-C33", "test_ticket114_authority_integration.test_114_a2_c33_public_correction_handoff_rejects_forged_scope", "the public owner-correction handoff revalidates the exact affected-object scope and clears transient plaintext when owner prepare rejects a forged revision"),
    ("114-A2-C34", "test_ticket114_authority_integration.test_114_a2_c34_public_correction_handoff_cleans_up_owner_rejection", "the public owner-correction handoff clears transient plaintext and authorization when the existing owner prepare path rejects a stale settings-object version"),

    # 114-A3 -- owner-scoped managed read, correction, and export.
    ("114-A3-C01", "test_ticket114_rights.test_114_a3_c01_non_owner_managed_read_rejected", "non-owner managed read is rejected"),
    ("114-A3-C02", "test_ticket114_rights.test_114_a3_c02_non_owner_correction_rejected", "non-owner correction is rejected"),
    ("114-A3-C03", "test_ticket114_rights.test_114_a3_c03_non_owner_export_rejected", "non-owner export is rejected"),
    ("114-A3-C04", "test_ticket114_rights.test_114_a3_c04_scoped_read_returns_only_current_authorized_objects", "scoped read returns only current authorized managed objects"),
    ("114-A3-C05", "test_ticket114_rights.test_114_a3_c05_correction_returns_pending_ticket112_draft", "correction returns an inheriting Ticket 112 draft without changing managed state"),
    ("114-A3-C06", "test_ticket114_rights.test_114_a3_c06_export_serializes_finite_snapshot", "export serializes a finite managed snapshot"),
    ("114-A3-C07", "test_ticket114_rights.test_114_a3_c07_export_round_trips_through_schema_parser", "serialized export parses through its strict schema"),
    ("114-A3-C08", "test_ticket114_rights.test_114_a3_c08_export_has_no_import_write_or_second_state_path", "export and rights service expose no import, write, seed, or second-state path"),
    ("114-A3-C09", "test_ticket114_rights.test_114_a3_c09_superseded_current_false_reference_rejected", "reference superseded in DailyHealthState is rejected"),
    ("114-A3-C10", "test_ticket114_rights.test_114_a3_c10_permission_revoked_reference_rejected", "reference whose permission was revoked is rejected"),
    ("114-A3-C11", "test_ticket114_rights.test_114_a3_c11_wrong_installation_reference_rejected", "reference bound to another installation is rejected"),
    ("114-A3-C12", "test_ticket114_contract.test_114_a3_c12_managed_object_contract_preserves_version_source_evidence_refs", "managed-object contract preserves version, source, and evidence references"),
    ("114-A3-C13", "test_ticket114_contract.test_114_a3_c13_correction_and_export_contracts_preserve_history_and_snapshot_metadata", "correction and export contracts preserve history and finite-snapshot metadata"),
    ("114-A3-C14", "test_ticket114_rights.test_114_a3_c14_stale_object_version_reference_rejected", "reference to a stale object version is rejected"),
    ("114-A3-C15", "test_ticket114_rights.test_114_a3_c15_correction_chain_keeps_stable_logical_object_ref", "a correction chain projects as one logical object whose root reference is stable while version and current evidence advance"),
    ("114-A3-C16", "test_ticket114_rights.test_114_a3_c16_read_missing_or_forged_permission_rejected", "managed read rejects missing or caller-forged permission values"),
    ("114-A3-C17", "test_ticket114_rights.test_114_a3_c17_correct_missing_or_forged_permission_rejected", "managed correction rejects missing or caller-forged permission values"),
    ("114-A3-C18", "test_ticket114_rights.test_114_a3_c18_export_missing_or_forged_permission_rejected", "managed export rejects missing or caller-forged permission values"),
    ("114-A3-C19", "test_ticket114_rights.test_114_a3_c19_draft_preserves_previous_value_and_logical_versions", "pending correction preserves the previous value, stable logical reference, and adjacent object versions"),
    ("114-A3-C20", "test_ticket114_authority_integration.test_114_a3_c20_finalized_ticket112_correction_revision_is_visible", "a correction draft becomes a new current logical-object revision only after the Ticket 112 prepare, commit, and finalize chain"),
    ("114-A3-C21", "test_ticket114_authority_integration.test_114_a3_c21_forged_pending_metadata_is_rebound_to_current_projection", "core rebinds correction target version, previous value, and revision metadata to the current managed projection before prepare"),
    ("114-A3-C22", "test_ticket114_rights.test_114_a3_c22_final_authoritative_state_recovers_correction_metadata_for_export", "the finalized DailyHealthState correction ledger projects complete revision metadata into managed export"),
    ("114-A3-C23", "test_ticket114_authority_integration.test_114_a3_c23_owner_correction_rejects_extra_evidence_scope", "owner correction prepare rejects a daily stage that also attempts an unrelated evidence write"),
    ("114-A3-C24", "test_ticket114_authority_integration.test_114_a3_c24_owner_correction_binds_actual_daily_source", "owner correction prepare binds revision source references to the actual Ticket 112 daily source"),
    ("114-A3-C25", "test_ticket114_authority_integration.test_114_a3_c25_public_rights_read_denies_wrong_owner_policy", "the public managed-rights read denies a plugin whose owner policy differs from core authority"),
    ("114-A3-C26", "test_ticket114_authority_integration.test_114_a3_c26_public_rights_read_denies_untrusted_peer", "the public managed-rights read denies an untrusted peer before exposing the projection"),
    ("114-A3-C27", "test_ticket114_authority_integration.test_114_a3_c27_public_export_roundtrips_final_correction_metadata", "public managed export round-trips the finalized correction and object lineage through its strict schema"),
    ("114-A3-C28", "test_ticket114_authority_integration.test_114_a3_c28_finalized_correction_prepare_receipt_is_body_free", "a finalized owner correction keeps exact prepare replay through a command digest without duplicating the correction or replacement body"),
    ("114-A3-C29", "test_ticket114_authority_integration.test_114_a3_c29_rejected_correction_prepare_receipt_is_body_free", "a rejected owner correction prepare stores only a command digest and exact response without a second correction-body copy"),
    ("114-A3-C30", "test_ticket114_authority_integration.test_114_a3_c30_correction_metadata_matches_actual_portrait_rejudgment", "owner correction metadata cannot claim an unrelated portrait scope when the verified complete draft rejudges a different portrait topic"),
    ("114-A3-C31", "test_ticket114_authority_integration.test_114_a3_c31_correction_rejects_extra_unsupported_affected_scope", "owner correction metadata cannot append an unsupported affected-object kind beyond the exact portrait rejudgment performed by Ticket 112"),

    # 114-A4 -- next-valid-local-day timezone transitions.
    ("114-A4-C01", "test_ticket114_settings_controls.test_114_a4_c01_dst_gap_uses_earliest_valid_instant", "DST gap resolves to the local date's earliest valid instant"),
    ("114-A4-C02", "test_ticket114_settings_controls.test_114_a4_c02_dst_fold_uses_earliest_valid_instant", "DST fold resolves to the earliest representation of the local date"),
    ("114-A4-C03", "test_ticket114_settings_controls.test_114_a4_c03_cross_day_uses_strict_next_local_date", "cross-day timezone change uses the strict next local date"),
    ("114-A4-C04", "test_ticket114_settings_controls.test_114_a4_c04_consecutive_pending_switches_keep_last_committed", "consecutive pending timezone switches keep only the last committed pending value"),
    ("114-A4-C05", "test_ticket114_settings_controls.test_114_a4_c05_restart_restores_committed_transition", "restart restores the committed timezone transition"),
    ("114-A4-C06", "test_ticket114_settings_controls.test_114_a4_c06_existing_review_key_is_not_rewritten", "existing review key is not rewritten by timezone transition"),
    ("114-A4-C07", "test_ticket114_settings_controls.test_114_a4_c07_old_days_are_not_backfilled_or_replayed", "old local days are neither backfilled nor replayed"),
    ("114-A4-C08", "test_ticket114_settings_controls.test_114_a4_c08_owner_can_see_effective_time", "owner-visible settings include timezone effective time"),
    ("114-A4-C09", "test_ticket114_contract.test_114_a4_c09_timezone_transition_binds_committed_request_next_date_and_effective_utc", "timezone-transition contract binds committed request time, next local date, and effective UTC"),
    ("114-A4-C10", "test_ticket114_settings_controls.test_114_a4_c10_transition_is_not_effective_before_due_time", "pending timezone remains inactive before its committed effective instant"),
    ("114-A4-C11", "test_ticket114_settings_controls.test_114_a4_c11_transition_activates_at_due_time", "pending timezone activates exactly at its committed effective instant"),
    ("114-A4-C12", "test_ticket114_settings_controls.test_114_a4_c12_restart_activates_persisted_transition_at_due_time", "restart preserves and activates the committed timezone transition when due"),
    ("114-A4-C13", "test_ticket114_authority_integration.test_114_a4_c13_core_activates_due_timezone_after_restart", "the production core activates a persisted timezone transition at its due instant after restart without another settings version"),

    # 114-A5 -- core-sealed business-fact status projection.
    ("114-A5-C01", "test_ticket114_status.test_114_a5_c01_active_truth_table", "complete confirmed core facts and an active diagnostic scope project active"),
    ("114-A5-C02", "test_ticket114_status.test_114_a5_c02_abnormal_truth_table", "confirmed core fault projects abnormal"),
    ("114-A5-C03", "test_ticket114_status.test_114_a5_c03_cannot_confirm_truth_table", "unknown core authority projects cannot-confirm"),
    ("114-A5-C04", "test_ticket114_status.test_114_a5_c04_forged_envelope_cannot_activate", "forged capability envelope cannot activate the product"),
    ("114-A5-C05", "test_ticket114_status.test_114_a5_c05_stale_or_old_generation_envelope_cannot_activate", "stale or old-generation envelope cannot activate the product"),
    ("114-A5-C06", "test_ticket114_status.test_114_a5_c06_unknown_domain_or_producer_cannot_activate", "unknown domain or producer cannot activate the product"),
    ("114-A5-C07", "test_ticket114_status.test_114_a5_c07_expired_envelope_cannot_activate", "expired envelope cannot activate the product"),
    ("114-A5-C08", "test_ticket114_status.test_114_a5_c08_missing_future_producer_cannot_activate", "missing not-yet-implemented required producer prevents active"),
    ("114-A5-C09", "test_ticket114_status.test_114_a5_c09_last_diagnostic_scope_invalid_is_abnormal", "loss of the last valid diagnostic scope projects abnormal"),
    ("114-A5-C10", "test_ticket114_status.test_114_a5_c10_single_isolated_noncore_fault_remains_active", "one isolated non-core fault does not hide otherwise active core capability"),
    ("114-A5-C11", "test_ticket114_status.test_114_a5_c11_identical_fact_replay_is_deterministic_and_emits_no_second_transition", "identical fact replay gives the same projection and no second transition"),
    ("114-A5-C12", "test_ticket114_contract.test_114_a5_c12_capability_envelope_is_core_sealed_body_free_and_rejects_liveness_proxies", "capability envelope is core-sealed, body-free, and cannot be built from liveness proxies"),
    ("114-A5-C13", "test_ticket114_status.test_114_a5_c13_same_generation_superseded_signed_revision_cannot_activate", "a superseded but validly signed revision in the expected generation cannot activate"),
    ("114-A5-C14", "test_ticket114_status.test_114_a5_c14_future_generation_envelope_cannot_activate", "an unexpected future capability generation cannot activate"),
    ("114-A5-C15", "test_ticket114_status.test_114_a5_c15_same_generation_conflicting_revisions_cannot_activate", "conflicting revisions in one capability generation cannot activate"),
    ("114-A5-C16", "test_ticket114_status.test_114_a5_c16_unknown_domain_input_cannot_activate", "an unknown capability domain cannot activate"),
    ("114-A5-C17", "test_ticket114_status.test_114_a5_c17_unexpected_producer_cannot_activate", "a producer outside the current requirement manifest cannot activate"),
    ("114-A5-C18", "test_ticket114_status.test_114_a5_c18_producer_contract_mismatch_cannot_activate", "a stale producer contract version cannot activate"),
    ("114-A5-C19", "test_ticket114_status.test_114_a5_c19_requiredness_mismatch_cannot_activate", "a producer cannot relabel a required core capability as non-core"),
    ("114-A5-C20", "test_ticket114_authority_integration.test_114_a5_c20_core_status_uses_real_authorities_and_keeps_future_domains_unknown", "core seals current authoritative business facts while not-yet-implemented task, delivery, safety, and diagnostic producers remain cannot-confirm"),
    ("114-A5-C21", "test_ticket114_authority_integration.test_114_a5_c21_status_transition_is_deduplicated_across_restart", "a business-status state change emits once and durable replay remains deduplicated after restart"),

    # 114-A6 -- prepare, commit, finalize, and writer-fence authority.
    ("114-A6-C01", "test_ticket114_authority_integration.test_114_a6_c01_prepare_failure_has_no_partial_result", "prepare failure creates no partial settings or rights result"),
    ("114-A6-C02", "test_ticket114_authority_integration.test_114_a6_c02_commit_failure_has_no_partial_result", "commit failure creates no partial settings or rights result"),
    ("114-A6-C03", "test_ticket114_authority_integration.test_114_a6_c03_finalize_failure_has_no_partial_result", "finalize failure creates no partial settings or rights result"),
    ("114-A6-C04", "test_ticket114_authority_integration.test_114_a6_c04_cas_conflict_rolls_back", "CAS conflict rolls back the prepared mutation"),
    ("114-A6-C05", "test_ticket114_authority_integration.test_114_a6_c05_unknown_freezes_without_guessing", "unknown authority result freezes without guessing or partial success"),
    ("114-A6-C06", "test_ticket114_authority_integration.test_114_a6_c06_stale_writer_fence_fails_before_write", "stale writer fence fails before a health write"),
    ("114-A6-C07", "test_ticket114_authority_integration.test_114_a6_c07_atomic_rollback_covers_settings_and_rights", "atomic rollback covers settings and managed-rights state together"),
    ("114-A6-C08", "test_ticket114_authority_integration.test_114_a6_c08_idempotent_replay_has_one_result", "idempotent replay has one authoritative result"),
    ("114-A6-C09", "test_ticket114_contract.test_114_a6_c09_authority_command_requires_permission_context_generation_and_fence", "authority command requires permission, context, current generation, and writer fence"),
    ("114-A6-C10", "test_ticket114_authority_integration.test_114_a6_c10_concurrent_owner_lease_rejects_without_partial_record", "a second owner mutation cannot bypass the single unresolved lease or leave a partial generic record"),
    ("114-A6-C11", "test_ticket114_authority_integration.test_114_a6_c11_terminal_settings_digest_rejects_same_version_substitution", "terminal settings digests form a legal historical version chain and reject a re-signed same-version aggregate substitution"),
    ("114-A6-C12", "test_ticket114_authority_integration.test_114_a6_c12_terminal_binds_exact_generic_transition_target", "a re-signed owner terminal whose revision or transition target differs from the generic final record fails integrity"),
    ("114-A6-C13", "test_ticket114_authority_integration.test_114_a6_c13_wrong_owner_fails_before_write", "a mutation bound to a different owner fails before any settings or rights write"),
    ("114-A6-C14", "test_ticket114_authority_integration.test_114_a6_c14_wrong_installation_fails_before_write", "a mutation bound to a different installation fails before any settings or rights write"),
    ("114-A6-C15", "test_ticket114_authority_integration.test_114_a6_c15_missing_settings_permission_fails_at_public_seam", "a hostile exact-type request missing settings permission is rejected by public canonicalization without a partial write"),
    ("114-A6-C16", "test_ticket114_authority_integration.test_114_a6_c16_missing_correction_permission_fails_at_public_seam", "a hostile exact-type request missing correction permission is rejected by public canonicalization without a partial write"),
    ("114-A6-C17", "test_ticket114_authority_integration.test_114_a6_c17_stale_current_head_generation_fails_before_write", "a stale current-head generation fails at the public prepare boundary before any write"),
    ("114-A6-C18", "test_ticket114_authority_integration.test_114_a6_c18_stale_settings_object_version_fails_before_write", "a stale settings object version fails before any settings or rights write"),
    ("114-A6-C19", "test_ticket114_authority_integration.test_114_a6_c19_legacy_manifest_migration_rechecks_signed_shape_inside_lock", "legacy manifest migration rechecks the signed legacy shape inside the same writer lock before re-signing"),
    ("114-A6-C20", "test_ticket114_authority_integration.test_114_a6_c20_fresh_manifest_rechecks_empty_domain_inside_lock", "fresh manifest creation rechecks both manifest absence and the empty state domain inside the same writer lock before signing"),
    ("114-A6-C21", "test_ticket114_authority_integration.test_114_a6_c21_owner_api_replays_daily_finalized_transition_after_restart", "after a daily causal path finalizes the shared transition across restart, owner commit and finalize replay their canonical responses without another CAS"),
    ("114-A6-C22", "test_ticket114_authority_integration.test_114_a6_c22_owner_api_resumes_daily_committed_transition_after_restart", "after a daily causal path commits the shared transition across restart, owner APIs recover the durable authority, finalize once, and replay without another CAS"),
    ("114-A6-C23", "test_ticket114_authority_integration.test_114_a6_c23_owner_commit_recovers_stopped_correction_without_body", "after a stopped correction owner prepare succeeds, restart loses all transient plaintext yet the standard owner commit/finalize APIs recover from the manifest-bound body-free owner reference plus the exact Ticket 112 prepared daily aggregate without raw source redelivery"),

    # 114-A7 -- managed consent-boundary view, drift pause, and re-consent.
    ("114-A7-C01", "test_ticket114_settings_controls.test_114_a7_c01_managed_read_shows_scope_recipient_enablement_consent", "managed read shows data scope, first-hop recipient, enablement, consent generation, and disclosure"),
    ("114-A7-C02", "test_ticket114_settings_controls.test_114_a7_c02_route_drift_pauses_affected_path", "first-hop route drift pauses the affected health path"),
    ("114-A7-C03", "test_ticket114_settings_controls.test_114_a7_c03_config_generation_drift_pauses_affected_path", "configuration-generation drift pauses the affected health path"),
    ("114-A7-C04", "test_ticket114_settings_controls.test_114_a7_c04_exact_redisclosure_is_required", "current route and configuration require exact redisclosure"),
    ("114-A7-C05", "test_ticket114_settings_controls.test_114_a7_c05_exact_reconsent_resumes_path", "exact owner re-consent resumes the affected path"),
    ("114-A7-C06", "test_ticket114_settings_controls.test_114_a7_c06_stale_disclosure_rejected", "stale disclosure is rejected"),
    ("114-A7-C07", "test_ticket114_settings_controls.test_114_a7_c07_stale_generation_rejected", "stale generation is rejected"),
    ("114-A7-C08", "test_ticket114_settings_controls.test_114_a7_c08_close_but_retain_returns_clarification_without_state_change", "ambiguous close-but-retain request returns clarification without state change"),
    ("114-A7-C09", "test_ticket114_contract.test_114_a7_c09_reconsent_contract_binds_route_config_generation_and_disclosure", "re-consent contract binds exact route, configuration generation, and disclosure"),
    ("114-A7-C10", "test_ticket114_settings_controls.test_114_a7_c10_old_route_configuration_fact_is_rejected", "route configuration facts older than the current configuration generation are rejected before mutation"),
    ("114-A7-C11", "test_ticket114_authority_integration.test_114_a7_c11_owner_cannot_submit_route_authority_fact", "the owner settings writer cannot author the core-owned route configuration fact"),
    ("114-A7-C12", "test_ticket114_authority_integration.test_114_a7_c12_core_route_fact_pauses_until_exact_reconsent", "a trusted core route fact pauses the public managed path until exact owner re-consent"),

    # 114-A8 -- exact execution-scope approval authority.
    ("114-A8-C01", "test_ticket114_settings_controls.test_114_a8_c01_full_field_approval_grant", "current owner grants a full-field execution-scope approval"),
    ("114-A8-C02", "test_ticket114_settings_controls.test_114_a8_c02_full_field_approval_revision", "current owner revises a full-field execution-scope approval"),
    ("114-A8-C03", "test_ticket114_settings_controls.test_114_a8_c03_full_field_approval_revoke", "current owner revokes a full-field execution-scope approval"),
    ("114-A8-C04", "test_ticket114_settings_controls.test_114_a8_c04_blank_approval_rejected", "blank execution-scope approval is rejected"),
    ("114-A8-C05", "test_ticket114_settings_controls.test_114_a8_c05_wildcard_approval_rejected", "wildcard execution-scope approval is rejected"),
    ("114-A8-C06", "test_ticket114_settings_controls.test_114_a8_c06_scope_expansion_requires_new_version_and_reapproval", "every scope-expansion dimension requires a new version and owner re-approval"),
    ("114-A8-C07", "test_ticket114_settings_controls.test_114_a8_c07_stale_generation_rejected", "old-generation approval command is rejected"),
    ("114-A8-C08", "test_ticket114_settings_controls.test_114_a8_c08_stale_version_rejected", "old-version approval command is rejected"),
    ("114-A8-C09", "test_ticket114_settings_controls.test_114_a8_c09_exact_replay", "exact approval-command replay returns the same result"),
    ("114-A8-C10", "test_ticket114_settings_controls.test_114_a8_c10_concurrent_revoke_linearizes_once", "concurrent approval revocation linearizes once"),
    ("114-A8-C11", "test_ticket114_settings_controls.test_114_a8_c11_unknown_revoke_freezes_consumption", "unknown revocation result freezes approval consumption"),
    ("114-A8-C12", "test_ticket114_contract.test_114_a8_c12_execution_scope_approval_contract_binds_all_required_fields", "execution-scope approval contract binds every required authority and limit field"),
    ("114-A8-C13", "test_ticket114_contract.test_114_a8_c13_only_current_owner_can_author_and_consumers_cannot_self_approve", "only current owner authors approval while consumers can only validate and consume"),
    ("114-A8-C14", "test_ticket114_settings_controls.test_114_a8_c14_route_mismatch_cannot_consume_approval", "approval consumption requires the exact bound route"),
    ("114-A8-C15", "test_ticket114_settings_controls.test_114_a8_c15_configuration_generation_mismatch_cannot_consume_approval", "approval consumption requires the exact bound configuration generation"),
    ("114-A8-C16", "test_ticket114_settings_controls.test_114_a8_c16_disclosure_version_mismatch_cannot_consume_approval", "approval consumption requires the exact bound disclosure version"),
    ("114-A8-C17", "test_ticket114_settings_controls.test_114_a8_c17_first_hop_recipient_mismatch_cannot_consume_approval", "approval consumption requires the exact first-hop recipient"),
    ("114-A8-C18", "test_ticket114_settings_controls.test_114_a8_c18_expired_approval_cannot_be_consumed", "approval consumption fails closed at its expiry instant"),
    ("114-A8-C19", "test_ticket114_settings_controls.test_114_a8_c19_task_mismatch_cannot_consume_approval", "approval consumption requires the exact task"),
    ("114-A8-C20", "test_ticket114_settings_controls.test_114_a8_c20_effect_request_mismatch_cannot_consume_approval", "approval consumption requires the exact effect request"),
    ("114-A8-C21", "test_ticket114_settings_controls.test_114_a8_c21_assignee_mismatch_cannot_consume_approval", "approval consumption requires the exact assignee"),
    ("114-A8-C22", "test_ticket114_settings_controls.test_114_a8_c22_purpose_mismatch_cannot_consume_approval", "approval consumption requires the exact owner-approved purpose"),
    ("114-A8-C23", "test_ticket114_settings_controls.test_114_a8_c23_data_category_outside_scope_cannot_consume_approval", "approval consumption rejects a data category outside the approved scope"),
    ("114-A8-C24", "test_ticket114_settings_controls.test_114_a8_c24_data_reference_outside_scope_cannot_consume_approval", "approval consumption rejects a stable data reference outside the approved scope"),
    ("114-A8-C25", "test_ticket114_settings_controls.test_114_a8_c25_external_effect_kind_mismatch_cannot_consume_approval", "approval consumption requires the exact external effect kind"),
    ("114-A8-C26", "test_ticket114_settings_controls.test_114_a8_c26_attempt_limit_is_validated_without_persisting_a_counter", "attempt limit is a pure consumption input and does not create Ticket 115 counter state"),
    ("114-A8-C27", "test_ticket114_settings_controls.test_114_a8_c27_minimum_interval_is_validated_without_persisting_contact_time", "contact interval is a pure consumption input and does not create Ticket 115 cadence state"),
    ("114-A8-C28", "test_ticket114_settings_controls.test_114_a8_c28_revoked_approval_cannot_be_consumed", "revoked approval cannot be consumed"),
    ("114-A8-C29", "test_ticket114_settings_controls.test_114_a8_c29_same_head_stale_writer_fence_rejects_every_approval_mutation", "same-head stale writer fence rejects grant, revise, and revoke before mutation"),

    # 114-A9 -- one current support contact and separate authority controls.
    ("114-A9-C01", "test_ticket114_settings_controls.test_114_a9_c01_managed_read_shows_current_contact_contract", "managed read shows the unique current contact and every authority status"),
    ("114-A9-C02", "test_ticket114_settings_controls.test_114_a9_c02_contact_replace", "contact replacement creates a new current contact boundary"),
    ("114-A9-C03", "test_ticket114_settings_controls.test_114_a9_c03_method_change", "contact-method change creates a new current contact boundary"),
    ("114-A9-C04", "test_ticket114_settings_controls.test_114_a9_c04_dedicated_pause", "support contact can be paused independently"),
    ("114-A9-C05", "test_ticket114_settings_controls.test_114_a9_c05_dedicated_resume", "support contact can be resumed independently"),
    ("114-A9-C06", "test_ticket114_settings_controls.test_114_a9_c06_alert_authority_grant", "alert authority can be granted independently"),
    ("114-A9-C07", "test_ticket114_settings_controls.test_114_a9_c07_alert_authority_revoke", "alert authority can be revoked independently"),
    ("114-A9-C08", "test_ticket114_settings_controls.test_114_a9_c08_alert_authority_reapprove", "alert authority can be re-approved exactly"),
    ("114-A9-C09", "test_ticket114_settings_controls.test_114_a9_c09_correction_authority_grant", "correction authority can be granted independently"),
    ("114-A9-C10", "test_ticket114_settings_controls.test_114_a9_c10_correction_authority_revoke", "correction authority can be revoked independently"),
    ("114-A9-C11", "test_ticket114_settings_controls.test_114_a9_c11_correction_authority_reapprove", "correction authority can be re-approved exactly"),
    ("114-A9-C12", "test_ticket114_settings_controls.test_114_a9_c12_stale_route_rejected", "old contact route is rejected"),
    ("114-A9-C13", "test_ticket114_settings_controls.test_114_a9_c13_stale_generation_rejected", "old contact generation is rejected"),
    ("114-A9-C14", "test_ticket114_settings_controls.test_114_a9_c14_non_owner_rejected", "non-owner contact command is rejected"),
    ("114-A9-C15", "test_ticket114_settings_controls.test_114_a9_c15_contact_controls_are_independent_of_general_controls", "contact controls remain independent of general support, recording, task, and notification controls"),
    ("114-A9-C16", "test_ticket114_contract.test_114_a9_c16_support_contact_contract_requires_identifiable_identity_and_all_status_fields", "support-contact contract requires identifiable identity and all displayed authority fields"),
    ("114-A9-C17", "test_ticket114_contract.test_114_a9_c17_replace_or_method_change_invalidates_old_authority_until_exact_approval", "replacement or method change invalidates old alert and correction authority until exact disclosure and approval"),
    ("114-A9-C18", "test_ticket114_settings_controls.test_114_a9_c18_managed_read_shows_support_contact_not_configured", "managed read exposes explicit not-configured contact state without fabricated identity or authority"),
    ("114-A9-C19", "test_ticket114_settings_controls.test_114_a9_c19_owner_configures_first_support_contact_from_not_configured", "owner can configure the first contact without automatically granting alert or correction authority"),
    ("114-A9-C20", "test_ticket114_settings_controls.test_114_a9_c20_old_contact_object_version_is_rejected_without_state_change", "old support-contact object version is rejected without changing state"),
    ("114-A9-C21", "test_ticket114_settings_controls.test_114_a9_c21_same_head_stale_writer_fence_is_rejected_before_mutation", "same-head stale writer fence is rejected before support-contact mutation"),
    ("114-A9-C22", "test_ticket114_settings_controls.test_114_a9_c22_owner_or_installation_cross_replay_invalidates_authority_binding", "support-contact authority binding cannot replay across owner or installation"),
    ("114-A9-C23", "test_ticket114_settings_controls.test_114_a9_c23_purpose_change_invalidates_authority_binding", "support-contact purpose change invalidates the old authority binding"),
    ("114-A9-C24", "test_ticket114_settings_controls.test_114_a9_c24_minimum_alert_fields_change_invalidates_authority_binding", "support-contact minimum-alert-field change invalidates the old authority binding"),
    ("114-A9-C25", "test_ticket114_authority_integration.test_114_a9_c25_ticket111_contact_starts_without_execution_authority", "a Ticket 111 configured contact enters Ticket 114 as one current object without automatically gaining alert or correction authority"),
    ("114-A9-C26", "test_ticket114_authority_integration.test_114_a9_c26_public_managed_read_configures_not_configured_contact", "public health-settings shows not-configured and configures one unapproved contact through the unique writer"),
    ("114-A9-C27", "test_ticket114_authority_integration.test_114_a9_c27_public_method_change_invalidates_and_reapproves_exactly", "public method change invalidates both old authorities and restores each only through its own exact owner approval"),
)


def _case_ids_for(module_name: str) -> frozenset[str]:
    prefix = module_name + "."
    return frozenset(
        case_id
        for case_id, test_name, _ in CASE_REGISTRY
        if test_name.startswith(prefix)
    )


CONTRACT_CASE_IDS = _case_ids_for("test_ticket114_contract")
SETTINGS_CONTROLS_CASE_IDS = _case_ids_for("test_ticket114_settings_controls")
RIGHTS_CASE_IDS = _case_ids_for("test_ticket114_rights")
STATUS_CASE_IDS = _case_ids_for("test_ticket114_status")
AUTHORITY_INTEGRATION_CASE_IDS = _case_ids_for(
    "test_ticket114_authority_integration"
)

MODULE_CASE_IDS = {
    "test_ticket114_contract": CONTRACT_CASE_IDS,
    "test_ticket114_settings_controls": SETTINGS_CONTROLS_CASE_IDS,
    "test_ticket114_rights": RIGHTS_CASE_IDS,
    "test_ticket114_status": STATUS_CASE_IDS,
    "test_ticket114_authority_integration": AUTHORITY_INTEGRATION_CASE_IDS,
}
