"""Compatibility/public name for the Ticket 115 task authority."""

from .tasks import (
    TASK_APPROVAL_STATUSES,
    TASK_INITIAL_PHASES,
    TASK_PHASES,
    TASK_PRIMARY_LABELS,
    TASK_SOURCE_KINDS,
    TASK_UNKNOWN_RESOLUTIONS,
    ManagedTask,
    TaskAcceptance,
    TaskAcceptanceCriterionProof,
    TaskApprovalBinding,
    TaskCandidate,
    TaskControlFact,
    TaskContractViolation,
    TaskEngine,
    TaskExternalBoundary,
    TaskLease,
    TaskRuntimeState,
    TaskTerminalFact,
    TaskTransition,
    TaskUnknownFact,
)
from .ticket115_contracts import (
    DeliveryEvidence,
    DeliveryEvidenceAuthority,
    MandatoryDeliveryLedger,
    MandatoryDeliveryRequest,
    TaskClaimLease,
    Ticket115ContractViolation,
)

HealthTask = ManagedTask
HealthTaskCandidate = TaskCandidate

__all__ = [
    "TASK_APPROVAL_STATUSES",
    "TASK_INITIAL_PHASES",
    "TASK_PHASES",
    "TASK_PRIMARY_LABELS",
    "TASK_SOURCE_KINDS",
    "TASK_UNKNOWN_RESOLUTIONS",
    "HealthTask",
    "HealthTaskCandidate",
    "ManagedTask",
    "TaskAcceptance",
    "TaskAcceptanceCriterionProof",
    "TaskApprovalBinding",
    "TaskCandidate",
    "TaskControlFact",
    "TaskClaimLease",
    "TaskContractViolation",
    "TaskEngine",
    "TaskExternalBoundary",
    "TaskLease",
    "TaskRuntimeState",
    "TaskTerminalFact",
    "TaskTransition",
    "TaskUnknownFact",
    "DeliveryEvidence",
    "DeliveryEvidenceAuthority",
    "MandatoryDeliveryLedger",
    "MandatoryDeliveryRequest",
    "Ticket115ContractViolation",
]
